### PR TITLE
put tests into functions

### PR DESCRIPTION
**Pull request by SamCox822**

### CODE REVIEW

**Comment by qcampbel** [comment]
why are we getting rid of streamlit? I thought it would be useful from user's end

**Comment by qcampbel** [comment]
are unit tests for RGy missing?

**Comment by SamCox822** [comment]
> are unit tests for RGy missing?

Maybe? I didn't remove any files here though so its not due to this PR

**Comment by SamCox822** [comment]
> why are we getting rid of streamlit? I thought it would be useful from user's end

Maybe, but it's unusable at the moment, we'll need to redo it fully. I think we should just remove it for now until we can fix it

**Review by qcampbel — APPROVED** [review]
Approved. we should add RGy unit tests asap though.

**Pull request merged**
