### PR TITLE
added vars to class before init in uniprot classes

### PR DESCRIPTION
**Pull request by SamCox822**
bug fix

### CODE REVIEW

**Comment by SamCox822** [comment]
the bug seems unrelated? @Jgmedina95 can you take a look & we can do it in another PR

**Comment by Jgmedina95** [comment]
It is a deprecation, simply 1.14 changed .simps to .simpson:
```DeprecationWarning: 'scipy.integrate.simps' is deprecated in favour of 'scipy.integrate.simpson' and will be removed in SciPy 1.14.0```
I'll change the function, and pin spicy version :)

**Comment by Jgmedina95** [comment]
Solving with PR #144

**Review by Jgmedina95 — APPROVED** [review]
lgtm

**Pull request merged**
